### ISSUE TITLE
is this module maintaining?

### ISSUE THREAD

**Issue by zj8487** [tj/rediskit#3]
it seems it has not be updated for long time!
but i think it is a great method to use with redis

**Comment by tj** [comment]
nope! I can add you if you're interested :D

**Comment by zj8487** [comment]
yes, it is a good idea! and it is my honor!

**Comment by tj** [comment]
added! what's your npm username?

**Comment by zj8487** [comment]
zj8487

**Comment by tj** [comment]
gah npm is being super broken again

**Comment by zj8487** [comment]
is it possible to enable travis for this module?
i have add the travis config

@tj

**Comment by tj** [comment]
sure! what's the conf

**Comment by zj8487** [comment]
conf have been add to the master
just enable it in site: https://travis-ci.org/profile
